
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      # Add your other environment variables here
      - MONGODB_URI=your_mongodb_uri
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: always

  # If you're using MongoDB, uncomment this service
  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db

# volumes:
#   mongodb_data: